name: 17 - 2 -custon Actions -composite
run-name: 17 - 2 - custon Actions -JS 
on:
    workflow_dispatch:
        inputs:
            target-env:
                description: Which environment to target for dependency installation
                type: choice
                options:
                    - dev
                    - prod



jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for dependency Updated
              uses: ./.github/actions/js-dependency-update
              